import { Metadata } from "next";
import { SidebarInset, SidebarProvider } from "@/laduny/components/ui/sidebar";
import Header from "@/laduny/components/shared/Header";
import AppSidebar from "@/laduny/components/shared/Sidebar";

export const metadata: Metadata = {
  title: "Dashboard POS System",
  description: "Generated by create next app",
};
export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section>
      <SidebarProvider>
        <AppSidebar />
        <SidebarInset>
          <Header />
          <div className="flex flex-1 flex-col gap-4 p-4 pt-0">{children}</div>
        </SidebarInset>
      </SidebarProvider>
    </section>
  );
}
