import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Sales Laduny POS System",
  description: "Generated by create next app",
};
export default function SalesLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <section>{children}</section>;
}
